{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "splunk-kubernetes-logging.serviceAccountName" . }}
  labels:
    app: {{ template "splunk-kubernetes-logging.name" . }}
    chart: {{ template "splunk-kubernetes-logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
  {{- else if .Values.global.kubernetes.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.global.kubernetes.automountServiceAccountToken }}
  {{- else }}
automountServiceAccountToken: "disabled" 
  {{- end -}}
{{- end -}}
