{{- $livenessProbeTimeoutSeconds := 55 }}
{{- if .Values.livenessProbe }}
  {{ if index .Values.livenessProbe.timeoutSeconds }}
    {{- $livenessProbeTimeoutSeconds = .Values.livenessProbe.timeoutSeconds }}
  {{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-kubernetes-metrics.fullname" . }}-k8sProbes
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  liveness.sh: |-
    #!/bin/sh

    if ! curl --max-time {{ $livenessProbeTimeoutSeconds }} --retry 0 http://localhost:9880/ ; then
      echo 'Fluentd http API not reachable'
      exit 1
    fi
  {{- if .Values.global.monitoring_agent_enabled }}
    if ! curl --max-time {{ $livenessProbeTimeoutSeconds }} --retry 0 http://localhost:24220/api/plugins.json ; then
      echo 'Fluentd monitoring API not usable'
      exit 1
    fi
  {{- end }}