apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "splunk-kubernetes-metrics.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    engine: fluentd
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: {{ template "splunk-kubernetes-metrics.fullname" . }}
  template:
    metadata:
      name: {{ template "splunk-kubernetes-metrics.fullname" . }}
      labels:
        name: {{ template "splunk-kubernetes-metrics.fullname" . }}
        app: {{ template "splunk-kubernetes-metrics.name" . }}
        chart: {{ template "splunk-kubernetes-metrics.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        engine: fluentd
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ template "splunk-kubernetes-metrics.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.image.usePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullsecretName}}
      {{- end }}
      containers:
      - name: splunk-fluentd-k8s-metrics
        image: {{ template "splunk-kubernetes-metrics.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          exec:
            command:
            - '/bin/sh'
            - '-c'
            - >
              LIVENESS_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-300};
              STUCK_THRESHOLD_SECONDS=${STUCK_THRESHOLD_SECONDS:-900};
              if [ ! -e /tmp/fluentd-buffers ];
              then
                exit 1;
              fi;
              touch -d "${STUCK_THRESHOLD_SECONDS} seconds ago" /tmp/marker-stuck;
              if [ -z "$(find /tmp/fluentd-buffers -type d -newer /tmp/marker-stuck -print -quit)" ];
              then
                rm -rf /var/log/fluentd-buffers;
                exit 1;
              fi;
              touch -d "${LIVENESS_THRESHOLD_SECONDS} seconds ago" /tmp/marker-liveness;
              if [ -z "$(find /tmp/fluentd-buffers -type d -newer /tmp/marker-liveness -print -quit)" ];
              then
                exit 1;
              fi;
        env:
          - name: KUBERNETES_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "splunk-kubernetes-metrics.secret" . }}
                key: splunk_hec_token
        resources:
{{ toYaml .Values.resources.fluent | indent 12 }}
        volumeMounts:
          - name: conf-configmap
            mountPath: /fluentd/etc
          - name: secrets
            mountPath: /fluentd/etc/splunk
            readOnly: true
      volumes:
      - name: conf-configmap
        configMap:
          name: {{ template "splunk-kubernetes-metrics.fullname" . }}
      - name: secrets
        secret:
          secretName: {{ template "splunk-kubernetes-metrics.secret" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
