apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "splunk-kubernetes-metrics.fullname" . }}-agg
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "splunk-kubernetes-metrics.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "splunk-kubernetes-metrics.name" . }}
        release: {{ .Release.Name }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/config: {{ include (print $.Template.BasePath "/configMapMetricsAggregator.yaml") . | sha256sum }}
        checksum/k8sProbes: {{ include (print $.Template.BasePath "/configmap-k8sProbes.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ template "splunk-kubernetes-metrics.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.aggregatorTolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.imageAgg.usePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imageAgg.pullsecretName}}
      {{- end }}
      containers:
      - name: splunk-fluentd-k8s-metrics-agg
        image: {{ template "splunk-kubernetes-metrics.imageAgg" . }}
        imagePullPolicy: {{ .Values.imageAgg.pullPolicy }}
        env:
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "splunk-kubernetes-metrics.secret" . }}
                key: splunk_hec_token
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SSL_CERT_FILE
            value: /fluentd/etc/splunk/hec_ca_file
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "/fluentd/liveness.sh"
          {{- if .Values.livenessProbe }}
            {{ if .Values.livenessProbe.initialDelaySeconds }} {{- (printf "initialDelaySeconds: %d" (int64 .Values.livenessProbe.initialDelaySeconds)) }} {{ else }}initialDelaySeconds: 30 {{end}}
            {{ if .Values.livenessProbe.periodSeconds }} {{- (printf "periodSeconds: %d" (int64 .Values.livenessProbe.periodSeconds)) }} {{ else }}periodSeconds: 60 {{end}}
            {{ if .Values.livenessProbe.timeoutSeconds }} {{- (printf "timeoutSeconds: %d" (int64 .Values.livenessProbe.timeoutSeconds)) }} {{ else }}timeoutSeconds: 55 {{end}}
            {{ if .Values.livenessProbe.failureThreshold }} {{- (printf "failureThreshold: %d" (int64 .Values.livenessProbe.failureThreshold)) }} {{ else }}failureThreshold: 5 {{end}}
          {{- else if .Values.global.livenessProbe }}
            {{ if .Values.global.livenessProbe.initialDelaySeconds }} {{- (printf "initialDelaySeconds: %d" (int64 .Values.global.livenessProbe.initialDelaySeconds)) }} {{ else }}initialDelaySeconds: 30 {{end}}
            {{ if .Values.global.livenessProbe.periodSeconds }} {{- (printf "periodSeconds: %d" (int64 .Values.global.livenessProbe.periodSeconds)) }} {{ else }}periodSeconds: 60 {{end}}
            {{ if .Values.global.livenessProbe.timeoutSeconds }} {{- (printf "timeoutSeconds: %d" (int64 .Values.global.livenessProbe.timeoutSeconds)) }} {{ else }}timeoutSeconds: 55 {{end}}
            {{ if .Values.global.livenessProbe.failureThreshold }} {{- (printf "failureThreshold: %d" (int64 .Values.global.livenessProbe.failureThreshold)) }} {{ else }}failureThreshold: 5 {{end}}
          {{- else }}
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 55
          failureThreshold: 5
          {{- end }}
        resources:
{{ toYaml .Values.resources.fluent | indent 12 }}
        volumeMounts:
          - name: conf-configmap
            mountPath: /fluentd/etc
          - name: secrets
            mountPath: /fluentd/etc/splunk
            readOnly: true
          - name: configmap-k8Probes
            mountPath: /fluentd/liveness.sh
            subPath: liveness.sh
      volumes:
      - name: conf-configmap
        configMap:
          name: {{ template "splunk-kubernetes-metrics.fullname" . }}-aggregator
      - name: secrets
        secret:
          secretName: {{ template "splunk-kubernetes-metrics.secret" . }}
      - name: configmap-k8Probes
        configMap:
          name: {{ template "splunk-kubernetes-objects.fullname" . }}-k8sProbes
          defaultMode: 0755
