apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "splunk-kubernetes-objects.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-objects.name" . }}
    chart: {{ template "splunk-kubernetes-objects.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "splunk-kubernetes-objects.name" . }}
      release: {{ .Release.Name }}
      engine: fluentd
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "splunk-kubernetes-objects.name" . }}
        release: {{ .Release.Name }}
        engine: fluentd
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
        checksum/k8sProbes: {{ include (print $.Template.BasePath "/configmap-k8sProbes.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ template "splunk-kubernetes-objects.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{ if .Values.image.usePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecretName }}
      {{ end }}
      containers:
      - name: splunk-fluentd-k8s-objects
        image: {{ template "splunk-kubernetes-objects.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "splunk-kubernetes-objects.secret" . }}
                key: splunk_hec_token
          - name: SSL_CERT_FILE
            value: /fluentd/etc/splunk/hec_ca_file
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "/fluentd/liveness.sh"
          {{- if .Values.global.splunk-kubernetes-objects.livenessProbe }}
          {{ if .Values.global.splunk-kubernetes-objects.livenessProbe.initialDelaySeconds }} {{- (printf "initialDelaySeconds: %d" (int64 .Values.global.splunk-kubernetes-objects.livenessProbe.initialDelaySeconds)) }} {{ else }}initialDelaySeconds: 30 {{end}}
          {{ if .Values.global.splunk-kubernetes-objects.livenessProbe.periodSeconds }} {{- (printf "periodSeconds: %d" (int64 .Values.global.splunk-kubernetes-objects.livenessProbe.periodSeconds)) }} {{ else }}periodSeconds: 60 {{end}}
          {{ if .Values.global.splunk-kubernetes-objects.livenessProbe.timeoutSeconds }} {{- (printf "timeoutSeconds: %d" (int64 .Values.global.splunk-kubernetes-objects.livenessProbe.timeoutSeconds)) }} {{ else }}timeoutSeconds: 55 {{end}}
          {{ if .Values.global.splunk-kubernetes-objects.livenessProbe.failureThreshold }} {{- (printf "failureThreshold: %d" (int64 .Values.global.splunk-kubernetes-objects.livenessProbe.failureThreshold)) }} {{ else }}failureThreshold: 5 {{end}}
          {{- else }}
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 55
          failureThreshold: 5
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: conf-configmap
          mountPath: /fluentd/etc
        {{- if .Values.checkpointFile.volume }}
        - name: checkpoints
          mountPath: /fluentd/var/checkpoints
        {{- end }}
        - name: secrets
          mountPath: /fluentd/etc/splunk
          readOnly: true
        - name: configmap-k8Probes
          mountPath: /fluentd/liveness.sh
          subPath: liveness.sh
      volumes:
      - name: conf-configmap
        configMap:
          name: {{ template "splunk-kubernetes-objects.fullname" . }}
      - name: secrets
        secret:
          secretName: {{ template "splunk-kubernetes-objects.secret" . }}
      {{- if .Values.checkpointFile.volume }}
      - name: checkpoints
{{ toYaml .Values.checkpointFile.volume | indent 8 }}
      {{- end -}}
      - name: configmap-k8Probes
        configMap:
          name: {{ template "splunk-kubernetes-objects.fullname" . }}-k8sProbes
          defaultMode: 0755
