{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "splunk-kubernetes-objects.serviceAccountName" . }}
  labels:
    app: {{ template "splunk-kubernetes-objects.name" . }}
    chart: {{ template "splunk-kubernetes-objects.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.serviceAccount.automountServiceAccountToken }}
    {{- if eq .Values.serviceAccount.automountServiceAccountToken "enabled" }}
automountServiceAccountToken: true
    {{- else }}
automountServiceAccountToken: false
    {{- end }}
  {{ else if .Values.global.kubernetes.automountServiceAccountToken }}
    {{- if eq .Values.global.kubernetes.automountServiceAccountToken "enabled" }}
automountServiceAccountToken: true
    {{- else }}
automountServiceAccountToken: false
    {{- end }}
  {{- else }}
automountServiceAccountToken: false
  {{- end }}
{{- end -}}
